<a href="https://colab.research.google.com/github/rigolabbe/desafioLATAMg69/blob/main/Desaf%C3%ADo_Estad%C3%ADstica_descriptiva_y_probabilidades_(Parte_II).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:

#cargamos la informaciion a DF Pandas
import numpy as np
import pandas as pd

data_world  = pd.read_csv("/content/sample_data/worldcup2014.csv")
data_world

,team,continent,group,group_pos,cantidad_juegos,juegos_ganados,juegos_empatados,juegos_perdidos,goles_favor,goles_contra,goles_diferencia,puntos,clasificado
0,Brazil,southamerica,A,1,3,2,1,0,7,2,5,7,1
1,Mexico,northamerica,A,2,3,2,1,0,4,1,3,7,1
2,Croatia,europe,A,3,3,1,0,2,6,6,0,3,0
3,Cameroon,africa,A,4,3,0,0,3,1,9,−8,0,0
4,Netherlands,europe,B,1,3,3,0,0,10,3,7,9,1
5,Chile,southamerica,B,2,3,2,0,1,5,3,2,6,1
6,Spain,europe,B,3,3,1,0,2,4,7,−3,3,0
7,Australia,asia,B,4,3,0,0,3,3,9,−6,0,0
8,Colombia,southamerica,C,1,3,3,0,0,9,2,7,9,1
9,Greece,europe,C,2,3,1,1,1,2,4,−2,4,1
10,Ivory Coast,africa,C,3,3,1,0,2,4,5,−1,3,0
11,Japan,asia,C,4,3,0,1,2,2,6,−4,1,0
12,Costa Rica,northamerica,D,1,3,2,1,0,4,1,3,7,1
13,Uruguay,southamerica,D,2,3,2,0,1,4,4,0,6,1
14,Italy,europe,D,3,3,1,0,2,2,3,−1,3,0
15,England,europe,D,4,3,0,1,2,2,4,−2,1,0
16,France,europe,E,1,3,2,1,0,8,2,6,7,1
17,Switzerland,europe,E,2,3,2,0,1,7,6,1,6,1
18,Ecuador,southamerica,E,3,3,1,1,1,3,3,0,4,0
19,Honduras,northamerica,E,4,3,0,0,3,1,8,−7,0,0
20,Argentina,southamerica,F,1,3,3,0,0,6,3,3,9,1
21,Nigeria,africa,F,2,3,1,1,1,3,3,0,4,1
22,Bosnia and Herzegovina,europe,F,3,3,1,0,2,4,4,0,3,0
23,Iran,asia,F,4,3,0,1,2,1,4,−3,1,0
24,Germany,europe,G,1,3,2,1,0,7,2,5,7,1
25,United States,northamerica,G,2,3,1,1,1,4,4,0,4,1
26,Portugal,europe,G,3,3,1,1,1,4,7,−3,4,0
27,Ghana,africa,G,4,3,0,1,2,4,6,−2,1,0
28,Belgium,europe,H,1,3,3,0,0,4,1,3,9,1
29,Algeria,africa,H,2,3,1,1,1,6,5,1,4,1
30,Russia,europe,H,3,3,0,2,1,2,3,−1,2,0
31,South Korea,asia,H,4,3,0,1,2,3,6,−3,1,0

1. Considerando el experimento de seleccionar un país participante al azar, se pide
determinar las probabilidades de los siguientes sucesos:

In [8]:
#a. pertenecer a África
data_worl_afri = data_world[data_world['continent']=='africa']
conteo = len(data_worl_afri)
print("La probabilidad de que pertenezca a africa es , " , conteo/len(data_world))

#b. pertenecer a Asia
data_worl_asia = data_world[data_world['continent']=='asia']
conteo = len(data_worl_asia)
print("La probabilidad de que pertenezca a asia  es , " , conteo/len(data_world))

#c. pertenecer a Europa
data_worl_europa = data_world[data_world['continent']=='europa']
conteo = len(data_worl_europa)
print("La probabilidad de que pertenezca a europa es , " , conteo/len(data_world))

#d. pertenecer a Norteamérica
data_worl_northamerica = data_world[data_world['continent']=='northamerica']
conteo = len(data_worl_northamerica)
print("La probabilidad de que pertenezca a northamerica es , " , conteo/len(data_world))

#e. pertenecer a Sudamérica
data_worl_southamerica = data_world[data_world['continent']=='southamerica']
conteo = len(data_worl_southamerica)
print("La probabilidad de que pertenezca a southamerica es , " , conteo/len(data_world))

#f. clasificar a segunda ronda
conteo = data_world["clasificado"].value_counts()
print("La probabildad que clasifique a segunda ronda es :" ,conteo[1]/len(data_world))

#g. ganar al menos un partido
data_worl_gana = data_world[data_world['juegos_ganados']>=1]
conteo = len(data_worl_gana)
print("La probabilidad de ganar al menos un partido es , " , conteo/len(data_world))

#h. pertenecer a África y clasificar a segunda ronda
conteo = len(data_worl_afri[data_worl_afri["clasificado"] ==1])
print("La probabilidad de pertenecer a África y clasificar a segunda ronda , " , conteo/len(data_world))

#i. pertenecer a Europa y clasificar a segunda ronda
conteo = len(data_worl_europa[data_worl_europa["clasificado"] ==1])
print("La probabilidad de pertenecer a europa  y clasificar a segunda ronda , " , conteo/len(data_world))

#j. pertenecer a Asia y clasificar a segunda ronda
conteo = len(data_worl_asia[data_worl_asia["clasificado"] ==1])
print("La probabilidad de pertenecer a asia  y clasificar a segunda ronda , " , conteo/len(data_world))

#k. pertenecer a Sudamérica y clasificar a segunda ronda
conteo = len(data_worl_southamerica[data_worl_southamerica["clasificado"] ==1])
print("La probabilidad de pertenecer a Sudamérica  y clasificar a segunda ronda , " , conteo/len(data_world))

#l. pertenecer a Norteamérica y clasificar a segunda ronda
conteo = len(data_worl_northamerica[data_worl_northamerica["clasificado"] ==1])
print("La probabilidad de pertenecer a northamerica  y clasificar a segunda ronda , " , conteo/len(data_world))

#m. pertenecer a África o clasificar a segunda ronda
conteo =len(data_world[(data_world['continent']=='africa') | (data_world['clasificado']==1)])
print("La probabilidad de pertenecer a africa o  clasificar a segunda ronda , " , conteo/len(data_world))


#n. pertenecer a Europa o clasificar a segunda ronda
conteo =len(data_world[(data_world['continent']=='europa') | (data_world['clasificado']==1)])
print("La probabilidad de pertenecer a europa o  clasificar a segunda ronda , " , conteo/len(data_world))

#o. pertenecer a Asia o clasificar a segunda ronda
conteo =len(data_world[(data_world['continent']=='asia') | (data_world['clasificado']==1)])
print("La probabilidad de pertenecer a europa o  clasificar a segunda ronda , " , conteo/len(data_world))

#p. pertenecer a Sudamérica o clasificar a segunda ronda
conteo =len(data_world[(data_world['continent']=='southamerica') | (data_world['clasificado']==1)])
print("La probabilidad de pertenecer a sudamerica o  clasificar a segunda ronda , " , conteo/len(data_world))

#q. pertenecer a Norteamérica o clasificar a segunda ronda
conteo =len(data_world[(data_world['continent']=='northamerica') | (data_world['clasificado']==1)])
print("La probabilidad de pertenecer a northamerica o  clasificar a segunda ronda , " , conteo/len(data_world))

#r. pertenecer a África y haber ganado al menos un partido
conteo = len(data_worl_afri[data_worl_afri['juegos_ganados']>=1])
print("La probabilidad de pertenecer a África y haber ganado al menos  1 partido , " , conteo/len(data_world))

#s. pertenecer a Europa y haber ganado al menos un partido
conteo = len(data_worl_europa[data_worl_europa['juegos_ganados']>=1])
print("La probabilidad de pertenecer a europa y haber ganado al menos  1 partido , " , conteo/len(data_world))

#t. pertenecer a Asia y haber ganado al menos un partido
conteo = len(data_worl_asia[data_worl_asia['juegos_ganados']>=1])
print("La probabilidad de pertenecer a asia y haber ganado al menos  1 partido , " , conteo/len(data_world))

#u. pertenecer a Sudamérica y haber ganado al menos un partido
conteo = len(data_worl_southamerica[data_worl_southamerica['juegos_ganados']>=1])
print("La probabilidad de pertenecer a sudamerica y haber ganado al menos  1 partido , " , conteo/len(data_world))

#v. pertenecer a Norteamérica y haber ganado al menos un partido

conteo = len(data_worl_northamerica[data_worl_northamerica['juegos_ganados']>=1])
print("La probabilidad de pertenecer a norteamerica y haber ganado al menos  1 partido , " , conteo/len(data_world))

#w. haber ganado al menos un partido y clasificar a segunda ronda
conteo =len(data_world[(data_world['juegos_ganados']>=1) & (data_world['clasificado']==1)])
print("La probabilidad haber ganado 1 partido  y   clasificar a segunda ronda , " , conteo/len(data_world))

La probabilidad de que pertenezca a africa es ,  0.15625
La probabilidad de que pertenezca a asia  es ,  0.125
La probabilidad de que pertenezca a europa es ,  0.0
La probabilidad de que pertenezca a northamerica es ,  0.125
La probabilidad de que pertenezca a southamerica es ,  0.1875
La probabildad que clasifique a segunda ronda es : 0.5
La probabilidad de ganar al menos un partido es ,  0.71875
La probabilidad de pertenecer a África y clasificar a segunda ronda ,  0.0625
La probabilidad de pertenecer a europa  y clasificar a segunda ronda ,  0.0
La probabilidad de pertenecer a asia  y clasificar a segunda ronda ,  0.0
La probabilidad de pertenecer a Sudamérica  y clasificar a segunda ronda ,  0.15625
La probabilidad de pertenecer a northamerica  y clasificar a segunda ronda ,  0.09375
La probabilidad de pertenecer a africa o  clasificar a segunda ronda ,  0.59375
La probabilidad de pertenecer a europa o  clasificar a segunda ronda ,  0.5
La probabilidad de pertenecer a europa o  clasificar a segunda ronda ,  0.625
La probabilidad de pertenecer a sudamerica o  clasificar a segunda ronda ,  0.53125
La probabilidad de pertenecer a northamerica o  clasificar a segunda ronda ,  0.53125
La probabilidad de pertenecer a África y haber ganado al menos  1 partido ,  0.09375
La probabilidad de pertenecer a europa y haber ganado al menos  1 partido ,  0.0
La probabilidad de pertenecer a asia y haber ganado al menos  1 partido ,  0.0
La probabilidad de pertenecer a sudamerica y haber ganado al menos  1 partido ,  0.1875
La probabilidad de pertenecer a norteamerica y haber ganado al menos  1 partido ,  0.09375
La probabilidad haber ganado 1 partido  y   clasificar a segunda ronda ,  0.5

In [37]:

# P (A | B ) = P (A  Y B )  / B

#a. pertenecer a Europa, si se sabe que clasificó
p_a_y_b =  len(data_world[(data_world["clasificado"] == 1)  &  (data_world['continent']=='europa')]) / len(data_world)
p_b = len(data_world[(data_world["clasificado"] == 1)])  / len(data_world)

print("Probabilidad que  pertenezca a europa , si se sabe que clasifico", p_a_y_b / p_b)

#b. pertenecer a Sudamérica, si se sabe que clasificó
p_a_y_b =  len(data_world[(data_world["clasificado"] == 1)  &  (data_world['continent']=='southamerica')]) / len(data_world)
p_b = len(data_world[(data_world["clasificado"] == 1)])  / len(data_world)

print("Probabilidad que  pertenezca a sudamerica , si se sabe que clasifico", p_a_y_b / p_b)


#c. pertenecer a África, si se sabe que ganó al menos un partido
p_a_y_b =  len(data_world[(data_world["juegos_ganados"] >= 1)  &  (data_world['continent']=='africa')]) / len(data_world)
p_b = len(data_world[(data_world["juegos_ganados"] >= 1)])  / len(data_world)

print("Probabilidad que  pertenezca a africa , si se sabe que ganó al menos un partido", p_a_y_b / p_b)


#d. haber ganado al menos un partido, si se sabe que clasificó
p_a_y_b =  len(data_world[(data_world["clasificado"] == 1)  &  (data_world['juegos_ganados']>=1)]) / len(data_world)
p_b = len(data_world[(data_world["clasificado"] == 1)])  / len(data_world)

print("Probabilidad haber ganado al menos un partido, si se sabe que clasificó", p_a_y_b / p_b)

#e. haber ganado al menos un partido, si se sabe que pertenece a Norteamérica
p_a_y_b =  len(data_world[(data_world["continent"] == 'northamerica')  &  (data_world['juegos_ganados']>=1)]) / len(data_world)
p_b = len(data_world[(data_world["continent"] == 'northamerica')])  / len(data_world)

print("Probabilidad haber ganado al menos un partido, si se sabe que pertenece a Norteamérica", p_a_y_b / p_b)

#f. NO haber clasificado, si se sabe que pertenece a África
p_a_y_b =  len(data_world[(data_world["continent"] == 'africa')  &  (data_world['clasificado']==0)]) / len(data_world)
p_b = len(data_world[(data_world["continent"] == 'africa')])  / len(data_world)

print("Probabilidad NO haber clasificado, si se sabe que pertenece a África", p_a_y_b / p_b)

Probabilidad que  pertenezca a europa , si se sabe que clasifico 0.0
Probabilidad que  pertenezca a sudamerica , si se sabe que clasifico 0.3125
Probabilidad que  pertenezca a africa , si se sabe que ganó al menos un partido 0.13043478260869565
Probabilidad haber ganado al menos un partido, si se sabe que clasificó 1.0
Probabilidad haber ganado al menos un partido, si se sabe que pertenece a Norteamérica 0.75
Probabilidad NO haber clasificado, si se sabe que pertenece a África 0.6