<a href="https://colab.research.google.com/github/rigolabbe/desafioLATAMg69/blob/main/Estadistica_Inferencial_RAL_G69.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('/content/sample_data/earnings.csv');
df

,height,weight,male,earn,earnk,ethnicity,education,mother_education,father_education,walk,exercise,smokenow,tense,angry,age
0,74,210.0,1,50000.0,50.0,White,16.0,16.0,16.0,3,3,2.0,0.0,0.0,45
1,66,125.0,0,60000.0,60.0,White,16.0,16.0,16.0,6,5,1.0,0.0,0.0,58
2,64,126.0,0,30000.0,30.0,White,16.0,16.0,16.0,8,1,2.0,1.0,1.0,29
3,65,200.0,0,25000.0,25.0,White,17.0,17.0,NaN,8,1,2.0,0.0,0.0,57
4,63,110.0,0,50000.0,50.0,Other,16.0,16.0,16.0,5,6,2.0,0.0,0.0,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1811,61,120.0,0,15000.0,15.0,White,18.0,18.0,18.0,6,1,2.0,0.0,0.0,82
1812,64,130.0,0,8000.0,8.0,White,12.0,12.0,12.0,1,1,1.0,7.0,7.0,33
1813,72,194.0,1,60000.0,60.0,White,12.0,12.0,12.0,2,1,2.0,0.0,0.0,50
1814,63,155.0,0,15000.0,15.0,Other,14.0,14.0,14.0,6,1,2.0,2.0,2.0,69
1815,68,150.0,1,6000.0,6.0,White,12.0,12.0,12.0,1,6,1.0,2.0,2.0,27

In [3]:
df.dropna()

,height,weight,male,earn,earnk,ethnicity,education,mother_education,father_education,walk,exercise,smokenow,tense,angry,age
0,74,210.0,1,50000.0,50.0,White,16.0,16.0,16.0,3,3,2.0,0.0,0.0,45
1,66,125.0,0,60000.0,60.0,White,16.0,16.0,16.0,6,5,1.0,0.0,0.0,58
2,64,126.0,0,30000.0,30.0,White,16.0,16.0,16.0,8,1,2.0,1.0,1.0,29
4,63,110.0,0,50000.0,50.0,Other,16.0,16.0,16.0,5,6,2.0,0.0,0.0,91
5,68,165.0,0,62000.0,62.0,Black,18.0,18.0,18.0,1,1,2.0,2.0,2.0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1811,61,120.0,0,15000.0,15.0,White,18.0,18.0,18.0,6,1,2.0,0.0,0.0,82
1812,64,130.0,0,8000.0,8.0,White,12.0,12.0,12.0,1,1,1.0,7.0,7.0,33
1813,72,194.0,1,60000.0,60.0,White,12.0,12.0,12.0,2,1,2.0,0.0,0.0,50
1814,63,155.0,0,15000.0,15.0,Other,14.0,14.0,14.0,6,1,2.0,2.0,2.0,69
1815,68,150.0,1,6000.0,6.0,White,12.0,12.0,12.0,1,6,1.0,2.0,2.0,27

In [18]:
df.columns

Index(['height', 'weight', 'male', 'earn', 'earnk', 'ethnicity', 'education',
       'mother_education', 'father_education', 'walk', 'exercise', 'smokenow',
       'tense', 'angry', 'age'],
      dtype='object')

In [19]:
df.drop_duplicates()

,height,weight,male,earn,earnk,ethnicity,education,mother_education,father_education,walk,exercise,smokenow,tense,angry,age
0,74,210.0,1,50000.0,50.0,White,16.0,16.0,16.0,3,3,2.0,0.0,0.0,45
1,66,125.0,0,60000.0,60.0,White,16.0,16.0,16.0,6,5,1.0,0.0,0.0,58
2,64,126.0,0,30000.0,30.0,White,16.0,16.0,16.0,8,1,2.0,1.0,1.0,29
3,65,200.0,0,25000.0,25.0,White,17.0,17.0,NaN,8,1,2.0,0.0,0.0,57
4,63,110.0,0,50000.0,50.0,Other,16.0,16.0,16.0,5,6,2.0,0.0,0.0,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1811,61,120.0,0,15000.0,15.0,White,18.0,18.0,18.0,6,1,2.0,0.0,0.0,82
1812,64,130.0,0,8000.0,8.0,White,12.0,12.0,12.0,1,1,1.0,7.0,7.0,33
1813,72,194.0,1,60000.0,60.0,White,12.0,12.0,12.0,2,1,2.0,0.0,0.0,50
1814,63,155.0,0,15000.0,15.0,Other,14.0,14.0,14.0,6,1,2.0,2.0,2.0,69
1815,68,150.0,1,6000.0,6.0,White,12.0,12.0,12.0,1,6,1.0,2.0,2.0,27

1. Considerando las variables earn, height y age, vamos a suponer que nuestro dataset
fuera una población completa. (Prepara los datos adecuadamente).

In [24]:
#                          PRUEBAS DE HIPOTESIS
#Hipotesis  nula es lo que tenemos como datos H0
#a. Realiza 5 pruebas con muestras de tamaño n = 25, en cada caso, con niveles
#de significancia diferentes pero inferiores a 0,1, para confirmar o rechazar las
#siguientes hipótesis considerando las alternativas. Crea para ello una fórmula
#que reciba los parámetros adecuados y resp

import numpy as np
import scipy.stats as stats

earn_dat= df['earn']
height_dat =df['height']
age_dat = df['age']

# pruebas de N=25
def prueba_hipotesis(data, H0, alternativa, nivel_confianza):
    muestra = np.random.choice(data, size=25, replace=False)
    if alternativa == '=':
        p_valor = stats.ttest_1samp(muestra, H0)[1]
    elif alternativa == '!=':
        _, p_valor = stats.ttest_1samp(muestra, H0)
    elif alternativa == '>':
        _, p_valor = stats.ttest_1samp(muestra, H0, alternative='greater')
    elif alternativa == '<':
        _, p_valor = stats.ttest_1samp(muestra, H0, alternative='less')

    if p_valor < nivel_confianza:
        resultado = f"con nivel de confianza del {(1 - nivel_confianza) * 100}%, se rechaza la hipótesis nula"
    else:
        resultado = f"con nivel de confianza del {(1 - nivel_confianza) * 100}%, se acepta la hipótesis nula"
    return resultado

# para las pruebas de hipótesis segun definicion en desafio
pruebas_earn = [(20000, '!='), (35000, '!='), (25000, '>'), (32000, '<')]
pruebas_height = [(55, '='), (68, '!='), (63, '>'), (70, '<')]
pruebas_age = [(44, '!='), (56, '!='), (51, '>'), (62, '<')]


#  pruebas  hipótesis para earn
print("Resultados para earn:")
for H0, alternativa in pruebas_earn:
    resultado = prueba_hipotesis(earn_dat, H0, alternativa, 0.1)
    print(f"H0: x {alternativa} {H0} - {resultado}")


#  pruebas hipótesis para height
print("Resultados para height:")
for H0, alternativa in pruebas_height:
    resultado = prueba_hipotesis(height_dat, H0, alternativa, 0.1)
    print(f"H0: x {alternativa} {H0} - {resultado}")


#  pruebas hipótesis para age
print("Resultados para age:")
for H0, alternativa in pruebas_age:
    resultado = prueba_hipotesis(age_dat, H0, alternativa, 0.1)
    print(f"H0: x {alternativa} {H0} - {resultado}")

Resultados para earn:
H0: x != 20000 - con nivel de confianza del 90.0%, se acepta la hipótesis nula
H0: x != 35000 - con nivel de confianza del 90.0%, se rechaza la hipótesis nula
H0: x > 25000 - con nivel de confianza del 90.0%, se acepta la hipótesis nula
H0: x < 32000 - con nivel de confianza del 90.0%, se rechaza la hipótesis nula
Resultados para height:
H0: x = 55 - con nivel de confianza del 90.0%, se rechaza la hipótesis nula
H0: x != 68 - con nivel de confianza del 90.0%, se rechaza la hipótesis nula
H0: x > 63 - con nivel de confianza del 90.0%, se rechaza la hipótesis nula
H0: x < 70 - con nivel de confianza del 90.0%, se rechaza la hipótesis nula
Resultados para age:
H0: x != 44 - con nivel de confianza del 90.0%, se acepta la hipótesis nula
H0: x != 56 - con nivel de confianza del 90.0%, se rechaza la hipótesis nula
H0: x > 51 - con nivel de confianza del 90.0%, se acepta la hipótesis nula
H0: x < 62 - con nivel de confianza del 90.0%, se rechaza la hipótesis nula

b. Calcula la media poblacional para cada variable. ¿Son correctos los
resultados obtenidos por tus pruebas?

In [17]:

media_earn = df['earn'].mean()
media_height = df['height'].mean()
media_age = df['age'].mean()

print(f"Media poblacional para earn: {media_earn}")
print(f"Media poblacional para height: {media_height}")
print(f"Media poblacional para age: {media_age}")

Media poblacional para earn: 21147.296255506608
Media poblacional para height: 66.56883259911895
Media poblacional para age: 42.934471365638764


 earn:

- La hipótesis nula \(H_0: \mu \neq 20000\) se acepta con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu \neq 35000\) se rechaza con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu > 25000\) se acepta con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu < 32000\) se acepta con un nivel de confianza del 90%.

height:

- La hipótesis nula \(H_0: \mu = 55\) se rechaza con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu \neq 68\) se acepta con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu > 63\) se rechaza con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu < 70\) se rechaza con un nivel de confianza del 90%.

age:

- La hipótesis nula \(H_0: \mu \neq 44\) se acepta con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu \neq 56\) se rechaza con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu > 51\) se acepta con un nivel de confianza del 90%.
- La hipótesis nula \(H_0: \mu < 62\) se rechaza con un nivel de confianza del 90%.

Estos resultados indican las decisiones tomadas respecto a las hipótesis nulas planteadas para cada variable con un nivel de confianza del 90%.

2. Crea una función que estime la proporción de hombres en el dataset, considerando
una muestra de 50 individuos, con niveles de significancia de 0,05 y 0,01. Escribe con
palabras tus resultados ejecutar la función e interpreta. Compara con la proporción
real.

In [23]:
def estimar_proporcion_hombres(data, muestra_size=50, nivel_confianza=0.05):
    muestra = np.random.choice(data, size=muestra_size, replace=False)
    proporcion_muestra = np.mean(muestra)

    _, p_valor = stats.ttest_1samp(muestra, 0.5)  # Comparar con la proporción real de hombres (0.5)

    if p_valor < nivel_confianza:
        resultado = f"El p-valor ({p_valor}) es menor que el nivel de confianza del {nivel_confianza * 100}%, por lo tanto, se rechaza la hipótesis nula. La proporción estimada de hombres en la muestra es {proporcion_muestra}."
    else:
        resultado = f"El p-valor ({p_valor}) es mayor que el nivel de confianza del {nivel_confianza * 100}%, por lo tanto, no hay suficiente evidencia para rechazar la hipótesis nula. La proporción estimada de hombres en la muestra es {proporcion_muestra}."

    return resultado

# Ejemplo de uso con la columna 'male' del DataFrame
proporcion_real = df['male'].mean()  # Proporción real de hombres en el dataset
resultado_05 = estimar_proporcion_hombres(df['male'], nivel_confianza=0.05)
resultado_01 = estimar_proporcion_hombres(df['male'], nivel_confianza=0.01)

print("Proporción real de hombres segun los datos:", proporcion_real)
print("Resultado para nivel de significancia 0.05:", resultado_05)
print("Resultado para nivel de significancia 0.01:", resultado_01)

Proporción real de hombres segun los datos: 0.3716960352422907
Resultado para nivel de significancia 0.05: El p-valor (0.2620558189926133) es mayor que el nivel de confianza del 5.0%, por lo tanto, no hay suficiente evidencia para rechazar la hipótesis nula. La proporción estimada de hombres en la muestra es 0.42.
Resultado para nivel de significancia 0.01: El p-valor (0.046587573163795186) es mayor que el nivel de confianza del 1.0%, por lo tanto, no hay suficiente evidencia para rechazar la hipótesis nula. La proporción estimada de hombres en la muestra es 0.36.

3. Considerando el dataset como una muestra, verifica si el género (male=1 significa
‘hombre”) influye sobre el sueldo “earn” de las personas. Explica y justifica tu
procedimiento.

In [21]:


# Separar  salarios  hombres y mujeres
earn_hombres = df[df['male'] == 1]['earn']
earn_mujeres = df[df['male'] == 0]['earn']  # si es cero es por que es mujer


# Realizar una prueba t para dos muestras independientes
t_stat, p_valor = stats.ttest_ind(earn_hombres, earn_mujeres)

# Establecer el nivel de significancia
nivel_confianza = 0.05

# Comparar el p-valor con el nivel de significancia
if p_valor < nivel_confianza:
    resultado = f"El p-valor ({p_valor}) es menor que el nivel de significancia del {nivel_confianza * 100}%, por lo tanto, se rechaza la hipótesis nula. Existe evidencia estadística para decir que el género influye en el sueldo de las personas en este dataset."
else:
    resultado = f"El p-valor ({p_valor}) es mayor que el nivel de significancia del {nivel_confianza * 100}%, por lo tanto, no hay suficiente evidencia para rechazar la hipótesis nula. No se puede concluir que el género influye en el sueldo de las personas en este dataset."

print(resultado)

El p-valor (1.2371946179054945e-40) es menor que el nivel de significancia del 5.0%, por lo tanto, se rechaza la hipótesis nula. Existe evidencia estadística para decir que el género influye en el sueldo de las personas en este dataset.