<a href="https://colab.research.google.com/github/rigolabbe/desafioLATAMg69/blob/main/Rodrigo_Araya_Labbe_Desafio_latam_Tipos_y_estructuras_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Crea un DataFrame con el archivo entregado.

In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv("/content/sample_data/resumen_resultados_astronautas.csv")
data

Crea la columna "IMC" usando la fórmula entregada

In [8]:
# IMC = m / h*h
# m = peso  h = altura
#  se genera el calculo llevando  la altura de cm a metros  y se crea en la columna IMC
data["IMC"] = round(data["peso"] /  ( (data["altura"] / 100) * (data["altura"] / 100 )  ),1)
data

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.1
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,24.4
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,23.4
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.2
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.7
5,Amaya de la Cruz,26,64,170,80,94,79,86,4,No,22.1
6,María Juderías,28,78,182,88,85,87,92,5,Si,23.5
7,Perla Alcocer,30,71,168,86,92,82,88,3,No,25.2
8,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.8
9,María José Franco,29,70,175,87,90,80,89,2,No,22.9
10,Emanuel Gálvez,27,73,181,84,89,84,87,3,Si,22.3
11,Alberto Graciani,28,62,163,81,93,77,85,5,No,23.3
12,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,22.4
13,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,23.8
14,Pablo Cotilla,27,75,178,86,87,85,89,2,Si,23.7
15,Pablo Capmany,29,69,171,82,94,80,88,4,No,23.6
16,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,22.2
17,Daniel Sánchez,26,63,167,80,93,78,85,4,No,22.6
18,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,22.1
19,José París,40,68,163,78,85,85,77,8,No,25.6
20,Kevin Pareja,27,61,177,85,90,87,79,2,Si,19.5
21,Estefania Manzanares,31,79,179,89,82,85,81,5,Si,24.7
22,Óliver Fonseca,38,80,164,77,88,90,89,9,No,29.7
23,Christopher Berganza,23,70,173,92,93,92,85,1,Si,23.4
24,Álvaro Espina,30,76,180,90,84,87,82,4,Si,23.5
25,Leonardo Magrina,39,65,171,79,92,90,85,8,No,22.2
26,Fernando Gálvez,25,72,168,88,88,89,83,2,Si,25.5
27,Sophie González,36,75,176,85,82,84,80,7,No,24.2
28,Alexia Gaos,21,69,169,93,94,93,86,0,Si,24.2
29,Fátima Varela,33,73,182,91,90,91,88,5,Si,22.0
30,Clara Arias,44,63,162,77,87,88,84,11,No,24.0
31,Paloma Berganza,28,62,174,87,85,87,78,3,Si,20.5

Crea la columna "promedio_evaluaciones" con el promedio de las 4 columnas
de evaluaciones. Si el IMC está entre 18.5 y 24.9, entonces el candidato
tendrá un IMC adecuado para ser astronauta. Filtra el DataFrame para
obtener solo aquellas filas donde el IMC esté dentro de los límites
entregados

In [15]:
promedio_eval  = (data["evaluacion_fisica"] +  data["evaluacion_psicologica"]  +  data["evaluacion_adaptativa"]  +  data["evaluacion_medica"] ) / 4

data["promedio_evaluaciones"] = promedio_eval

IMC_rango = data[(data["IMC"] >= 18.5 )&(data["IMC"]<= 24.9)]
IMC_rango

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.1,87.00
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,24.4,86.25
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,23.4,86.50
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.2,89.50
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.7,87.25
5,Amaya de la Cruz,26,64,170,80,94,79,86,4,No,22.1,84.75
6,María Juderías,28,78,182,88,85,87,92,5,Si,23.5,88.00
8,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.8,89.75
9,María José Franco,29,70,175,87,90,80,89,2,No,22.9,86.50
10,Emanuel Gálvez,27,73,181,84,89,84,87,3,Si,22.3,86.00
11,Alberto Graciani,28,62,163,81,93,77,85,5,No,23.3,84.00
12,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,22.4,89.50
13,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,23.8,89.25
14,Pablo Cotilla,27,75,178,86,87,85,89,2,Si,23.7,86.75
15,Pablo Capmany,29,69,171,82,94,80,88,4,No,23.6,86.00
16,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,22.2,87.25
17,Daniel Sánchez,26,63,167,80,93,78,85,4,No,22.6,84.00
18,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,22.1,89.75
20,Kevin Pareja,27,61,177,85,90,87,79,2,Si,19.5,85.25
21,Estefania Manzanares,31,79,179,89,82,85,81,5,Si,24.7,84.25
23,Christopher Berganza,23,70,173,92,93,92,85,1,Si,23.4,90.50
24,Álvaro Espina,30,76,180,90,84,87,82,4,Si,23.5,85.75
25,Leonardo Magrina,39,65,171,79,92,90,85,8,No,22.2,86.50
27,Sophie González,36,75,176,85,82,84,80,7,No,24.2,82.75
28,Alexia Gaos,21,69,169,93,94,93,86,0,Si,24.2,91.50
29,Fátima Varela,33,73,182,91,90,91,88,5,Si,22.0,90.00
30,Clara Arias,44,63,162,77,87,88,84,11,No,24.0,84.00
31,Paloma Berganza,28,62,174,87,85,87,78,3,Si,20.5,84.25

El promedio de las 4 evaluaciones debe ser mayor o igual a 87. Filtra el
DataFrame resultante y agrega esta condición al filtro aplicado en el paso
anterior

In [17]:
 # a lo contenido en la variable de calculo anterior ademas se filtra por  promedio de evaluaciones acalculado anteriormente
 IMC_rango =  IMC_rango[(IMC_rango["promedio_evaluaciones"] >= 87 ) ]
 IMC_rango

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.1,87.00
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.2,89.50
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.7,87.25
6,María Juderías,28,78,182,88,85,87,92,5,Si,23.5,88.00
8,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.8,89.75
12,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,22.4,89.50
13,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,23.8,89.25
16,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,22.2,87.25
18,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,22.1,89.75
23,Christopher Berganza,23,70,173,92,93,92,85,1,Si,23.4,90.50
28,Alexia Gaos,21,69,169,93,94,93,86,0,Si,24.2,91.50
29,Fátima Varela,33,73,182,91,90,91,88,5,Si,22.0,90.00

Reinicia el índice del DataFrame resultante

In [19]:
# reindexamos los indices del resultado filtrado
IMC_rango.reset_index(drop=True, inplace=True)
IMC_rango

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.1,87.00
1,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.2,89.50
2,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.7,87.25
3,María Juderías,28,78,182,88,85,87,92,5,Si,23.5,88.00
4,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.8,89.75
5,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,22.4,89.50
6,Cristóbal Miralles,31,72,174,88,91,86,92,6,No,23.8,89.25
7,Nicolás Cambeiro,29,68,175,88,90,81,90,2,No,22.2,87.25
8,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,22.1,89.75
9,Christopher Berganza,23,70,173,92,93,92,85,1,Si,23.4,90.50
10,Alexia Gaos,21,69,169,93,94,93,86,0,Si,24.2,91.50
11,Fátima Varela,33,73,182,91,90,91,88,5,Si,22.0,90.00

Modifica el valor de la columna "califica", para que diga "Si" en todas las filas del
DataFrame resultante

In [20]:
IMC_rango["califica"] = "Si"
IMC_rango

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.1,87.00
1,Valentina Tasis,30,65,175,90,91,85,92,2,Si,21.2,89.50
2,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.7,87.25
3,María Juderías,28,78,182,88,85,87,92,5,Si,23.5,88.00
4,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.8,89.75
5,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,22.4,89.50
6,Cristóbal Miralles,31,72,174,88,91,86,92,6,Si,23.8,89.25
7,Nicolás Cambeiro,29,68,175,88,90,81,90,2,Si,22.2,87.25
8,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,22.1,89.75
9,Christopher Berganza,23,70,173,92,93,92,85,1,Si,23.4,90.50
10,Alexia Gaos,21,69,169,93,94,93,86,0,Si,24.2,91.50
11,Fátima Varela,33,73,182,91,90,91,88,5,Si,22.0,90.00

Exporta el DataFrame resultante a un archivo .csv separado por comas con el
nombre "astronautas_calificados.csv".

In [21]:
# el archivo queda por default descargado con separador de comas
data.to_csv("/content/sample_data/astronautas_calificados.csv",index=False)